name: lint & swag

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  merge_group:
    branches:
      - '*'

jobs:
  linter:
    name: Run linters
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repo
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.1
          cache: false
      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2
          args: --timeout=5m
  swagger:
    name: Verify Swagger Updated
    runs-on: ubuntu-latest
    needs: linter
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    - name: Install swag
      run: go install github.com/swaggo/swag/cmd/swag@latest
    - name: Run swag init
      run: swag init
    - name: Check for changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "Swagger documentation is not up to date"
          git status
          git diff
          exit 1
        else
          echo "Swagger documentation is up to date"
        fi
